// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzSNYEiwyl_dy3BobXoamGtEu6bomlAts',
    appId: '1:559186514508:web:410a907ac5837a60f3dae9',
    messagingSenderId: '559186514508',
    projectId: 'todo-a7a92',
    authDomain: 'todo-a7a92.firebaseapp.com',
    storageBucket: 'todo-a7a92.firebasestorage.app',
    measurementId: 'G-8295FZQ66R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYzw78DnYgppd4jQ8Ozl06Fp-a3k7ZtHk',
    appId: '1:559186514508:android:167e3a9098185966f3dae9',
    messagingSenderId: '559186514508',
    projectId: 'todo-a7a92',
    storageBucket: 'todo-a7a92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw0fgLAbRkVA4XBgxHaBIDDjBh8quBlhA',
    appId: '1:559186514508:ios:4a176c3db12f6588f3dae9',
    messagingSenderId: '559186514508',
    projectId: 'todo-a7a92',
    storageBucket: 'todo-a7a92.firebasestorage.app',
    androidClientId: '559186514508-haa1lmh1qiuue2qq1m15hudvjqn1gu4b.apps.googleusercontent.com',
    iosClientId: '559186514508-cud24lk98hmc7186jlccklev85qea4qg.apps.googleusercontent.com',
    iosBundleId: 'com.test.ajmal.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw0fgLAbRkVA4XBgxHaBIDDjBh8quBlhA',
    appId: '1:559186514508:ios:4a176c3db12f6588f3dae9',
    messagingSenderId: '559186514508',
    projectId: 'todo-a7a92',
    storageBucket: 'todo-a7a92.firebasestorage.app',
    androidClientId: '559186514508-haa1lmh1qiuue2qq1m15hudvjqn1gu4b.apps.googleusercontent.com',
    iosClientId: '559186514508-cud24lk98hmc7186jlccklev85qea4qg.apps.googleusercontent.com',
    iosBundleId: 'com.test.ajmal.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzSNYEiwyl_dy3BobXoamGtEu6bomlAts',
    appId: '1:559186514508:web:6e86f94f8edcfad5f3dae9',
    messagingSenderId: '559186514508',
    projectId: 'todo-a7a92',
    authDomain: 'todo-a7a92.firebaseapp.com',
    storageBucket: 'todo-a7a92.firebasestorage.app',
    measurementId: 'G-FZ7G5BVM5X',
  );
}
